# Generated by Django 3.1.3 on 2020-12-12 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь(сотрудник)')),
            ],
        ),
        migrations.CreateModel(
            name='Initiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
            },
        ),
        migrations.CreateModel(
            name='Researched_objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('images1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото1')),
                ('images2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото2')),
                ('images3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото3')),
                ('additional_information', models.TextField(blank=True, verbose_name='Дополнительные сведения')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Type_Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
            },
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_work', models.CharField(max_length=150, verbose_name='Вид работы')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тип материала',
                'verbose_name_plural': 'Типы материалов',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150, verbose_name='Номер')),
                ('serial_number', models.CharField(max_length=150, verbose_name='Номер дела')),
                ('receipt_date', models.DateField(blank=True, verbose_name='Дата регистрации')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата исполнения')),
                ('additional_information', models.TextField(blank=True, verbose_name='Дополнительные сведения')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='Дата продления')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='work.employee', verbose_name='Сотрудник')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.initiator', verbose_name='Инициатор')),
                ('researched_objects', models.ManyToManyField(blank=True, null=True, to='work.Researched_objects', verbose_name='Объекты')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.subdivision', verbose_name='Подразделение')),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.typework', verbose_name='Эксп/Исл')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='researched_objects',
            name='type_objects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.type_objects', verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='initiator',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='initiator',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.rank', verbose_name='Звание'),
        ),
        migrations.AddField(
            model_name='initiator',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.subdivision', verbose_name='Подразделение'),
        ),
    ]
