# Generated by Django 3.1.3 on 2020-12-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='researched_objects',
            field=models.ManyToManyField(blank=True, to='work.Researched_objects', verbose_name='Объекты'),
        ),
    ]
