# Generated by Django 3.1.3 on 2020-12-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20201212_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='initiator',
            options={'verbose_name': 'Инициатор', 'verbose_name_plural': 'Инициаторы'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='family_name',
            field=models.CharField(default=123, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=123, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='work.rank', verbose_name='Звание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='second_name',
            field=models.CharField(default=123, max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
