# Generated by Django 3.1.3 on 2020-12-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20201214_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=9, max_length=50, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
